language: node_js

node_js:
  - 6

cache:
  directories:
  - $HOME/.npm

services:
  - docker

before_script:
  - make build

script:
  - make test

after_script:
  - make clean

notifications:
  email: false
